import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/globals.css'
import NavBar from '@/component/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const bodyClasses = `${inter.className} bg-white dark:bg-gray-900 dark:text-white`

  return (
    <html lang="en">
      <body className={bodyClasses}>
        {children}
      </body>
    </html>
  )
}
